<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20241202100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add AI-generated image fields for storing cat images generated by Gemini Imagen';
    }

    public function up(Schema $schema): void
    {
        // Add AI image base64 content (LONGTEXT for base64 encoded images)
        $this->addSql('ALTER TABLE cat ADD ai_image_base64 LONGTEXT DEFAULT NULL');

        // Add AI image prompt (to track what prompt was used)
        $this->addSql('ALTER TABLE cat ADD ai_image_prompt VARCHAR(255) DEFAULT NULL');

        // Add timestamp for when AI image was generated
        $this->addSql('ALTER TABLE cat ADD ai_image_generated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE cat DROP ai_image_base64');
        $this->addSql('ALTER TABLE cat DROP ai_image_prompt');
        $this->addSql('ALTER TABLE cat DROP ai_image_generated_at');
    }
}
